### ISSUE TITLE
Runtime Error when using webpack (svelte-loader)

### ISSUE THREAD

**Issue by philippone** [melt-ui/melt-ui#1293]
### Describe the bug

When using webpack (with svelte-loader) to bundle an application, then the following runtime error occurs:

> `Uncaught TypeError: Cannot read properties of undefined (reading 'noop')
    at Module.noop (index.js:93:101)
    at eval (makeElement.js:91:74)
    at makeElement (makeElement.js:94:7)
    at eval (makeElement.js:47:26)
    at ./node_modules/@melt-ui/svelte/dist/internal/helpers/makeElement.js (main.6edd7ae6.js:2335:1)
    at __webpack_require__ (main.6edd7ae6.js:3550:32)
    at fn (main.6edd7ae6.js:3733:21)
    at eval (index.js:118:73)
    at ./node_modules/@melt-ui/svelte/dist/internal/helpers/index.js (main.6edd7ae6.js:2269:1)
    at __webpack_require__ (main.6edd7ae6.js:3550:32)`

It works with melt-ui <= "0.72.0".

### Reproduction

https://stackblitz.com/edit/melt-webpack-noop-undefined?file=src%2Findex.html

`npm install`
`npm run start`
Error visible in browser console

### System Info

```bash
System:
    OS: macOS 15.1.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 598.27 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.13.1/bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    pnpm: 8.6.6 - ~/.nvm/versions/node/v22.1.0/bin/pnpm
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1.1
  npmPackages:
    @melt-ui/svelte: 0.72.0 => 0.72.0 (above this version is not working anymore)
    @sveltejs/kit: 2.6.2 => 2.6.2 
    svelte: 4.2.19 => 4.2.19
```

### Severity

blocking an upgrade

**Comment by aqmebrak** [comment]
Also stuck by this issue and can't switch to Vite easily as Svelte is executed by symfony-ux inside the Symfony Encore module (which uses Webpack as bundler)
